### ISSUE TITLE
Regression on new install: UnboundLocalError: local variable 'httpc' referenced before assignment

### ISSUE THREAD

**Issue by brianredbeard** [GAM-team/got-your-back#218]
Please confirm the following:
[x] I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
[x] I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

GYB v1.28 is currently breaking on x86_64 Linux hosts with the error when run via the installer:
(_Note:  The project creation repeatedly fails_)

```
This Linux distribution uses glibc 2.28
Using GYB compiled against glibc2.23

Checking GitHub URL https://api.github.com/repos/jay0lee/got-your-back/releases for  GYB release...

Getting file and download URL...

Downloading file gyb-1.28-linux-x86_64-glibc2.23.tar.xz from https://github.com/jay0lee/got-your-back/releases/download/v1.28/gyb-1.28-linux-x86_64-glibc2.23.tar.xz to /tmp/tmp.KGOjfdQCB0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0   1804      0 --:--:-- --:--:-- --:--:--  1799
100 7389k  100 7389k    0     0   690k      0  0:00:10  0:00:10 --:--:-- 1398k
Extracting archive to ..

Finished extracting GYB archive.

skipping profile update.

Can you run a full browser on this machine? (usually Y for MacOS, N for Linux if you SSH into this machine) Y

Please enter your email address: brian.harrington@coreos.com
Traceback (most recent call last):
  File "gyb.py", line 2065, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1405, in main
    doCreateProject()
  File "gyb.py", line 841, in doCreateProject
    crm = getCRMService(login_hint)
  File "gyb.py", line 661, in getCRMService
    credentials = oauth2client.tools.run_flow(flow=flow, storage=storage, flags=flags, http=httpc)
UnboundLocalError: local variable 'httpc' referenced before assignment
[16597] Failed to execute script gyb
Project creation failed. Trying again.
...
Traceback (most recent call last):
  File "gyb.py", line 2065, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 1405, in main
    doCreateProject()
  File "gyb.py", line 841, in doCreateProject
    crm = getCRMService(login_hint)
  File "gyb.py", line 661, in getCRMService
    credentials = oauth2client.tools.run_flow(flow=flow, storage=storage, flags=flags, http=httpc)
UnboundLocalError: local variable 'httpc' referenced before assignment
[16597] Failed to execute script gyb
Project creation failed. Trying again.
```

Similarly, running directly from a downloaded release errors as follows:
```
(gyb) [/tmp/gyb]$ ./gyb/gyb --action create-project --email brian.harrington@coreos.com
Traceback (most recent call last):
  File "gyb.py", line 2065, in <module>
  File "gyb.py", line 1405, in main
  File "gyb.py", line 841, in doCreateProject
  File "gyb.py", line 661, in getCRMService
UnboundLocalError: local variable 'httpc' referenced before assignment
[17962] Failed to execute script gyb
```

**Comment by dsl101** [comment]
Same on Windows. Looking through git blame, it seems [this update](https://github.com/jay0lee/got-your-back/commit/8ed74814704a42ed58158f2a7e056e456ae2a9cb) might have missed one and line 661 should read:

```
credentials = oauth2client.tools.run_flow(flow=flow, storage=storage, flags=flags, http=_createHttpObj())
```
