### ISSUE TITLE
Restore errors

### ISSUE THREAD

**Issue by bryantech** [GAM-team/got-your-back#340]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. During restore I get this error. ValueError: Token used too early, 1641481785 < 1641481885
2.
3.

Expected outcome (what are you trying to do?):
Restore email
Actual outcome (what errors or bad behavior do you see instead?):

I have tried with gyb versions, 1.41-1.52. 1.36 allows for restore but that isn't a permanent fix.

**Comment by aaronadamsCA** [comment]
I've noticed `gyb` is incredibly sensitive to the system clock being ahead, and it looks like yours might be a solid 100 seconds ahead.

Either wait two minutes before pasting your token, or set your clock back two minutes, and I think you should be good to go.

**Comment by jay0lee** [comment]
This is fixed in the latest release.

**Comment by dsakura** [comment]
Im receiving this error too, with last version of the software
```
Traceback (most recent call last):
  File "gyb.py", line 2817, in <module>
  File "gyb.py", line 2040, in main
  File "gyb.py", line 420, in getValidOauth2TxtCredentials
  File "gyb.py", line 532, in requestOAuthAccess
  File "gyb.py", line 547, in writeCredentials
  File "gyb.py", line 562, in _getValueFromOAuth
  File "gyb.py", line 556, in _decodeIdToken
  File "google\oauth2\id_token.py", line 160, in verify_oauth2_token
  File "google\oauth2\id_token.py", line 132, in verify_token
  File "google\auth\jwt.py", line 302, in decode
  File "google\auth\jwt.py", line 216, in _verify_iat_and_exp
google.auth.exceptions.InvalidValue: Token used too early, 1719118946 < 1719118978. Check that your computer's clock is set correctly.
```
Thank you
