### ISSUE TITLE
Running gyb-setup.bat error: UnboundLocalError: local variable 'local_server' referenced before assignment

### ISSUE THREAD

**Issue by c-hri-s** [GAM-team/got-your-back#370]
Trying to download mail for a GSuite Free user and seeing an error on setup. Tried both gyb-setup.bat and the command below. Using the latest gyb.zip on Windows 11:

`C:\Desktop\email backup>gyb --action create-project --email email@customdomain.co.uk`
`Process Process-2:`
`Traceback (most recent call last):`
`  File "multiprocessing\process.py", line 315, in _bootstrap`
`  File "multiprocessing\process.py", line 108, in run`
`  File "gyb.py", line 894, in _wait_for_http_client`
`UnboundLocalError: local variable 'local_server' referenced before assignment`

gyb then just hangs.

**Comment by c-hri-s** [comment]
Tried again with a fresh download with a @gmail.com account instead of a GSuite account .. same thing:

`D:\Gmail Backup>gyb --action create-project --email <email>@gmail.com`
`Process Process-2:`
`Traceback (most recent call last):`
`  File "multiprocessing\process.py", line 315, in _bootstrap`
`  File "multiprocessing\process.py", line 108, in run`
`  File "gyb.py", line 894, in _wait_for_http_client`
`UnboundLocalError: local variable 'local_server' referenced before assignment`

**Comment by c-hri-s** [comment]
1.55 works okay

1.60 gives this error `gyb.exe: error: unrecognized arguments: --multiprocessing-fork parent_pid=5316 pipe_handle=708`

1.61 and 1.6.2 give the error in the above comments

**Comment by c-hri-s** [comment]
For whatever reason, tried again today and it works fine (other than the OAUTH setup procedure you need to go through which isn't documented).
