### ISSUE TITLE
Failed to execute script 'gyb' due to unhandled exception!

### ISSUE THREAD

**Issue by quack79** [GAM-team/got-your-back#448]
**Please confirm the following:**
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
Yes
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki
Yes

**Full steps to reproduce the issue:**
Backed up mail from gmail.com, trying to restore into a GSuite Legacy account - no issues
Using the command:
> gyb --email me@mydomain.com --action restore --local-folder GYB-GMail-Backup-xxx@gmail.com --label-restored "Restore"

**Expected outcome (what are you trying to do?):**
Mail is restored

**Actual outcome (what errors or bad behavior do you see instead?):**
Using backup folder GYB-GMail-Backup-xxx@gmail.com
Traceback (most recent call last):
  File "gyb.py", line 2817, in <module>
  File "gyb.py", line 2254, in main
  File "gyb.py", line 1990, in convert_timestamp
  File "_strptime.py", line 555, in _strptime_datetime
  File "_strptime.py", line 336, in _strptime
ValueError: unconverted data remains: .156000
[40044] Failed to execute script 'gyb' due to unhandled exception!

**Comment by quack79** [comment]
After some testing with the python source, and adding in a print(val) to see what it was actually falling over on, I have found a few dates written into the database that it cannot process.

For example:
b'2013-03-24 17:34:40.756000'

I am now using DB Browser for SQLite to edit the date fields and will try running the code again.

**Comment by davidvankemenade** [comment]
I came across exactly the same issue. Thanks @quack79 for poining me to the manual edit route so that I can continue for now.

**Comment by daniellefisla** [comment]
See https://github.com/GAM-team/got-your-back/issues/459

**Comment by grego-r-b** [comment]
Manual edit worked great. Thanks @quack79
