### ISSUE TITLE
Strptime datetime error

### ISSUE THREAD

**Issue by gustavohellwig** [GAM-team/got-your-back#456]
Hi,
What should I do in this case?
I have many cases where, when I'm trying to backup and recover, it's showing this:

Traceback (most recent call last):
  File "gyb.py", line 2817, in <module>
  File "gyb.py", line 2254, in main
  File "gyb.py", line 1990, in convert_timestamp
  File "_strptime.py", line 555, in _strptime_datetime
  File "_strptime.py", line 336, in _strptime
ValueError: unconverted data remains: .371000

I'm running this:
  gyb --email $secondaryaccountr --service-account --local-folder "$BackupFolderPath\$secondaryaccount"  --search before:2010/12/31
  gyb --email $newemailaddress --service-account --action restore --local-folder "$BackupFolderPath\$secondaryaccount" --label-restored "$secondaryaccount"
}

Any suggestions?
Thank you

Using the Latest version.

**Comment by ffrants** [comment]
Having the same issue

**Comment by gustavohellwig** [comment]
FYI. The version 1.74 doesn't have this error.
