### ISSUE TITLE
Token used too early

### ISSUE THREAD

**Issue by dsakura** [GAM-team/got-your-back#469]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/got-your-back. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

Full steps to reproduce the issue:
1. I confirmed that the computer and cell phone clocks were correct.
2. I started with the code --action estimate
3. 
4.

Expected outcome (what are you trying to do?): 
Testing the program with the --action stimate to be able to backup my email.

Actual outcome (what errors or bad behavior do you see instead?):
This error:
```
The authentication flow has completed.
Traceback (most recent call last):
  File "gyb.py", line 2817, in <module>
  File "gyb.py", line 2040, in main
  File "gyb.py", line 420, in getValidOauth2TxtCredentials
  File "gyb.py", line 532, in requestOAuthAccess
  File "gyb.py", line 547, in writeCredentials
  File "gyb.py", line 562, in _getValueFromOAuth
  File "gyb.py", line 556, in _decodeIdToken
  File "google\oauth2\id_token.py", line 160, in verify_oauth2_token
  File "google\oauth2\id_token.py", line 132, in verify_token
  File "google\auth\jwt.py", line 302, in decode
  File "google\auth\jwt.py", line 216, in _verify_iat_and_exp
google.auth.exceptions.InvalidValue: Token used too early, 1719119384 < 1719119416. Check that your computer's clock is set correctly.
[11348] Failed to execute script 'gyb' due to unhandled exception!
```
Many thanks!

**Comment by jay0lee** [comment]
The error is telling you the time on your local computer is wrong. Make sure the time on your local computer is correct.
